"""add_agent_tables

Revision ID: 5117ca03ce23
Revises: 0010
Create Date: 2026-03-24 16:36:23.886114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5117ca03ce23"
down_revision: Union[str, None] = "0010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_sessions",
        sa.Column("rid", sa.Text(), nullable=False),
        sa.Column("ontology_rid", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("domain", sa.Text(), nullable=True),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("scope_hint", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ontology_rid"],
            ["ontologies.rid"],
        ),
        sa.PrimaryKeyConstraint("rid"),
    )
    op.create_table(
        "agent_audit_logs",
        sa.Column("rid", sa.Text(), nullable=False),
        sa.Column("session_rid", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_rid"], ["agent_sessions.rid"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("rid"),
    )
    op.create_index(
        "idx_agent_audit_logs_session",
        "agent_audit_logs",
        ["session_rid", "created_at"],
        unique=False,
    )
    op.create_table(
        "agent_messages",
        sa.Column("rid", sa.Text(), nullable=False),
        sa.Column("session_rid", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_rid"], ["agent_sessions.rid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rid"),
    )
    op.create_index(
        "idx_agent_messages_session", "agent_messages", ["session_rid", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sync_jobs",
        "dataset_rid",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "sync_jobs",
        "object_type_rid",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "sync_jobs", "rid", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "object_instances",
        "source_dataset_rid",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "object_instances",
        "object_type_rid",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "object_instances",
        "rid",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index("idx_agent_messages_session", table_name="agent_messages")
    op.drop_table("agent_messages")
    op.drop_index("idx_agent_audit_logs_session", table_name="agent_audit_logs")
    op.drop_table("agent_audit_logs")
    op.drop_table("agent_sessions")
    # ### end Alembic commands ###
