-- 01-schema.sql — Finance sample: 5 tables for Link Type testing
-- Generated by generate.py — DO NOT EDIT MANUALLY

CREATE TABLE companies (
  id              VARCHAR(10)  PRIMARY KEY COMMENT '股票代码 e.g. 600519',
  name            VARCHAR(100) NOT NULL    COMMENT '公司简称',
  sector          VARCHAR(50)              COMMENT '所属行业',
  market_cap      DOUBLE                   COMMENT '总市值(亿元)',
  country         VARCHAR(50) DEFAULT '中国',
  founded_year    INT                      COMMENT '上市年份',
  latest_report_id VARCHAR(20)             COMMENT 'FK → rating_reports.id (for BO link)',
  is_active       BOOLEAN DEFAULT TRUE,
  created_at      DATETIME DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='A股上市公司';

CREATE TABLE analysts (
  id              VARCHAR(20)  PRIMARY KEY COMMENT '分析师ID e.g. ANL-001',
  name            VARCHAR(100) NOT NULL    COMMENT '分析师姓名(虚构)',
  firm            VARCHAR(100)             COMMENT '所属券商(真实)',
  specialty       VARCHAR(50)              COMMENT '覆盖行业',
  company_id      VARCHAR(10)              COMMENT 'FK → companies.id (主覆盖公司)',
  latest_report_id VARCHAR(20)             COMMENT 'FK → rating_reports.id (for BO link)',
  hire_date       DATE                     COMMENT '入职日期',
  is_active       BOOLEAN DEFAULT TRUE,
  created_at      DATETIME DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='证券分析师';

CREATE TABLE rating_reports (
  id              VARCHAR(20)  PRIMARY KEY COMMENT '研报ID e.g. RPT-00001',
  analyst_id      VARCHAR(20)              COMMENT '分析师ID(信息列)',
  company_id      VARCHAR(10)              COMMENT '公司代码(信息列)',
  rating          VARCHAR(20)              COMMENT '评级: 买入/增持/中性/减持/卖出',
  target_price    DOUBLE                   COMMENT '目标价(元)',
  report_date     DATE                     COMMENT '研报日期',
  summary         VARCHAR(500)             COMMENT '摘要',
  created_at      DATETIME DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='研报评级(Backing Object)';

CREATE TABLE funds (
  id              VARCHAR(20)  PRIMARY KEY COMMENT '基金代码 e.g. 000001',
  name            VARCHAR(100) NOT NULL    COMMENT '基金简称',
  fund_type       VARCHAR(30)              COMMENT '基金类型: 股票型/混合型/指数型',
  aum             DOUBLE                   COMMENT '资产规模(亿元)',
  inception_date  DATE                     COMMENT '成立日期',
  manager         VARCHAR(100)             COMMENT '基金经理',
  is_active       BOOLEAN DEFAULT TRUE,
  created_at      DATETIME DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公募基金';

CREATE TABLE fund_company_holdings (
  fund_id         VARCHAR(20) NOT NULL     COMMENT '→ funds.id',
  company_id      VARCHAR(10) NOT NULL     COMMENT '→ companies.id',
  PRIMARY KEY (fund_id, company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='基金持仓(Join Table)';
