-- 02-seed-companies.sql — 50 real A-share companies

INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600519', '贵州茅台', '白酒Ⅱ', 18596.21, '中国', 2001, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('000858', '五 粮 液', '白酒Ⅱ', 4067.54, '中国', 1998, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('000568', '泸州老窖', '白酒Ⅱ', 1591.61, '中国', 1994, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601398', '工商银行', '银行Ⅱ', 26338.42, '中国', 2006, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601288', '农业银行', '银行Ⅱ', 23658.85, '中国', 2010, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600036', '招商银行', '银行Ⅱ', 10118.2, '中国', 2002, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601166', '兴业银行', '银行Ⅱ', 4023.06, '中国', 2007, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601818', '光大银行', '银行Ⅱ', 1973.46, '中国', 2010, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601318', '中国平安', '保险Ⅱ', 11197.77, '中国', 2007, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601601', '中国太保', '保险Ⅱ', 3896.24, '中国', 2007, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600030', '中信证券', '证券Ⅱ', 3840.0, '中国', 2003, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601688', '华泰证券', '证券Ⅱ', 1782.81, '中国', 2010, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('000002', '万  科Ａ', '房地产开发', 560.74, '中国', 1991, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('001979', '招商蛇口', '房地产开发', 878.16, '中国', 2015, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('300750', '宁德时代', '电池', 18483.67, '中国', 2018, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601012', '隆基绿能', '光伏设备', 1423.92, '中国', 2012, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600438', '通威股份', '光伏设备', 830.17, '中国', 2004, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600104', '上汽集团', '乘用车', 1681.76, '中国', 1997, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('002594', '比亚迪', '乘用车', 9378.86, '中国', 2011, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601238', '广汽集团', '乘用车', 803.53, '中国', 2012, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600276', '恒瑞医药', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('000538', '云南白药', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('300760', '迈瑞医疗', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('603259', '药明康德', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('002415', '海康威视', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600588', '用友网络', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('603501', '豪威集团', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('002230', '科大讯飞', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('000651', '格力电器', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('000333', '美的集团', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('002032', '苏 泊 尔', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600887', '伊利股份', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('002304', '洋河股份', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('603288', '海天味业', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600019', '宝钢股份', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601899', '紫金矿业', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('603993', '洛阳钼业', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600900', '长江电力', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601985', '中国核电', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('000063', '中兴通讯', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600183', '生益科技', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('002049', '紫光国微', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600585', '海螺水泥', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('000963', '华东医药', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600309', '万华化学', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('601006', '大秦铁路', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600029', '南方航空', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('300413', '芒果超媒', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('600893', '航发动力', NULL, NULL, '中国', NULL, TRUE);
INSERT INTO companies (id, name, sector, market_cap, country, founded_year, is_active) VALUES ('000977', '浪潮信息', NULL, NULL, '中国', NULL, TRUE);
